# 청와대 국민청원 데이터
## 결측치 다루기 
* 데이터 출처 : https://github.com/akngs/petitions
* 전체 행 중에서 5%는 임의 필드 1개에 결측치 삽입
* 범주(category)가 '육아/교육'이고 투표수(votes)가 50건 초과이면 20% 확률로 투표수에 결측치 넣기
* 나머지는 전체 데이터와 동일

=> 위와 같이 임의로 만들어진 결측치를 다뤄본다.

In [ ]:
# 출력데이터가 지저분하게 보이지 않도록 warnings을 불러왔다.
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
from plotnine import *
print(pd.__version__)
print(np.__version__)

0.21.0
1.14.0

In [3]:
petitions = pd.read_csv('data/petition_corrupted.csv')
# 데이터의 크기가 어느정도인지 본다.
petitions.shape

(159770, 8)

In [4]:
# 위에서 3개의 데이터만 따로 추출해 본다.
# 그런데 컬럼명이 없는 것을 알 수 있다. 그래서 컬럼명을 지정해 주고 다시 불러오도록 한다.
petitions.head(3)

,21,2017-08-19,2017-11-17,0,9,안전/환경,스텔라 데이지호에 대한 제안입니다.,"스텔라 데이지호에 대한 제안입니다.\n3월31일 스텔라 데이지호가 침몰하고 5달째가 되고 있습니다.\n저는 우리가 너무 일찍 포기한 것이 아닌가 하는 생각을 갖고 있습니다.\n그리고, 추후 이 사고에 대한 확실한 해결이 없다면 나중에는 문재인 정부에 커다란 부담이 될 수도 있다는 생각에 이 글을 쓰게 되었습니다.\n가족들이 지금까지 갖고 있는 희망은 발견되지 않은 구명벌(땟목)에 선원들이 살아있지 않을까 하는 겁니다.\n생존 훈련받은 선원들이 대부분이고 구명벌에는 지붕과 생존도구가 구비되어있기 때문에 오랜 기간 버틸 수 있을 거라 보는 겁니다.\n이전 정권이 대선이전에 서둘러 수색을 중단한 탓도 있고, 정권교체 후 재수색이 있었지만,\n태평양, 3000m 수심이라는 데서, 애초 우리가 마음속에서 너무 일찍 포기한 게 아닌가 하는 생각이 듭니다.\n멕시코에서는 14개월 동안 표류하다 구조된 어부도 있고,\n과태말라에서 요트가 전복되어 태평양을 117일간 표류하던 어떤 부부가 한국어선에 의해 구조되는 일도 있었다는데,\n구명벌을 찾을 때 까지 포기하면 안된다고 생각합니다.\n구명벌이 침몰당시 분리된 것이 맞는지 확인하고,\n선박의 침몰 원인을 찾기 위해서도 심해를 탐사할 수 있는 장비를 통한 수색도 필요하다고 생각합니다.\n선박의 침몰에 대해서는 선사의 노후선박 개조와 사전 균열 등, 의혹이 제기되고 있는 상황입니다.\n구명벌이 선박에서 분리되지 못했다면 구명벌 수색은 필요 없는 것이 되고 침몰원인만 확인하면 되는 것입니다.\n물론 불가능하거나 실패할 수도 있지만 적어도 정부가 할 수 있는 모든 걸 했다는 것을 보여줘야 한다고 봅니다.\n침몰 당시 자동발신 조난신호의 위치나 수동발신 조난신호 발생위치가 확인되고 있고, AIS나 레이다, 인공위성사진 등을 이용하면 침몰위치 특정은 어려운 것이 아니고,\n현재 유인 심해 탐사정의 심해탐사기록이 일본 6500m, 중국 7,062m인 걸 보면 아주 불가능한 일은 아닐 수도 있다고 봅니다.\n애초에 사고가 발생했을 때 해수부는 국방부에 협조를 구해서 구조용 군함과 헬기를 지원 받고, 주변국과의 협조로 전방위적인 구명벌 수색을 했어야 한다고 봅니다.\n하지만, 지금은 구명벌이 조류와 바람에 의해 어디로 흘러갔을지 모르기 때문에 좀 더 넓은 지역에 대한 지속적인 구조용 선박과 헬기에 의한 수색과 주변 무인도에 대한 수색이 필요하다고 봅니다.\n나중에라도 구명벌이 발견되고 죽어있는 시신만 발견되었을 때 국가가 아무것도 안하고 있었다면 그 비난은 모두 현 정부에 주어지게 될 것이기 때문입니다.\n물론, 정부가 욕을 먹는 것은 작은 겁니다.\n중요한건 “사람이 먼저다”라는 가치를 지키는 것입니다.\n이런 공간을 마련해 주셔서 감사합니다."
0,22,2017-08-19,2017-11-17,0,17.0,기타,비리제보처를 만들어주세요.,현 정부에 국민들이 가장 원하는 것은 부패척결입니다. 우리 사회에 각종 비리들이 ...
1,23,2017-08-19,2017-09-03,0,0.0,미래,제2의 개성공단,"만일 하시는 대통령님 및 각 부처 장관님,주무관님들 안녕하세요!!\n전남 목포에서 ..."
2,24,2017-08-19,2017-08-26,0,53.0,일자리,공공기관 무조건적인 정규직전환을 반대합니다.,현정부에서 정규직 일자리를 늘리는 것에 찬성합니다. 그런데 공공기관 비정규직들은 인...

### 컬럼명 지정

In [5]:
column_names = ['article_id','start','end','answered','votes','category','title','content']
petitions = pd.read_csv('data/petition_corrupted.csv', names = column_names, header=None)
petitions.head()

,article_id,start,end,answered,votes,category,title,content
0,21,2017-08-19,2017-11-17,0,9.0,안전/환경,스텔라 데이지호에 대한 제안입니다.,스텔라 데이지호에 대한 제안입니다.\n3월31일 스텔라 데이지호가 침몰하고 5달째가...
1,22,2017-08-19,2017-11-17,0,17.0,기타,비리제보처를 만들어주세요.,현 정부에 국민들이 가장 원하는 것은 부패척결입니다. 우리 사회에 각종 비리들이 ...
2,23,2017-08-19,2017-09-03,0,0.0,미래,제2의 개성공단,"만일 하시는 대통령님 및 각 부처 장관님,주무관님들 안녕하세요!!\n전남 목포에서 ..."
3,24,2017-08-19,2017-08-26,0,53.0,일자리,공공기관 무조건적인 정규직전환을 반대합니다.,현정부에서 정규직 일자리를 늘리는 것에 찬성합니다. 그런데 공공기관 비정규직들은 인...
4,25,2017-08-19,2017-09-03,0,0.0,미래,제2의 개성공단,"만일 하시는 대통령님 및 각 부처 장관님,주무관님들 안녕하세요!!\n전남 목포에서 ..."

* 컬럼명은 위와 같이 지정해 줄 수도 있지만, 하나씩 타이핑하기 귀찮다면 우리에겐 `petition_sampled.csv`가 있으니 해당 csv에서 샘플 컬럼을 불러오도록 한다.
* data 폴더에 있는 샘플 파일명을 확인한다.

In [6]:
%ls data

petition.csv            petition_corrupted.csv  petition_sampled.csv

In [7]:
# 샘플파일에는 컬럼이 존재한다.
petition_sample = pd.read_csv('data/petition_sampled.csv')
print(petition_sample.shape)
petition_sample.head()

(8029, 8)

,article_id,start,end,answered,votes,category,title,content
0,58,2017-08-19,2017-11-17,0,21,일자리,국토교통부와 한국주택협회가 행한 부당한 행위와 권력남용에 대한 내용을 청원드립니다.,안녕하세요? 존경하고 지지하는 문재인 대통령님!\n저는 성남시 분당구 정자동 주택전...
1,63,2017-08-20,2017-09-04,0,1,보건복지,살려주세요..,안녕하십니까?\n저는 올해 63세된 홀로 사는 늙은 여자입니다...\n작년 중복날 ...
2,136,2017-08-20,2017-11-18,0,4,육아/교육,고등학교 교육 내용 수준을 낮춰주시고 실용적인 내용을 담아주세요!,저는 광주에 사는 중3 학생입니다. 고등학교 가기 직전의 학년이라 어느 때보다 고등...
3,141,2017-08-20,2017-08-27,0,0,기타,한국문화에 창조적요소를 심자,안녕하십니까\n저는 92년 한국을 알게된 종국동포 입니다.\n[저는 한 중소기업에...
4,148,2017-08-20,2017-11-18,0,7,외교/통일/국방,다문화정책 및 할랄 인증 제도,대한민국과 국민을 위해 밤낮 없이 수고하시는 대통령을 비롯한 위정자 분들께\n대한민...

In [8]:
# 컬럼명을 지정해 준다
petition_columns = petition_sample.columns

In [9]:
petitions = pd.read_csv('data/petition_corrupted.csv', names = petition_columns, header=None)
petitions.head()

,article_id,start,end,answered,votes,category,title,content
0,21,2017-08-19,2017-11-17,0,9.0,안전/환경,스텔라 데이지호에 대한 제안입니다.,스텔라 데이지호에 대한 제안입니다.\n3월31일 스텔라 데이지호가 침몰하고 5달째가...
1,22,2017-08-19,2017-11-17,0,17.0,기타,비리제보처를 만들어주세요.,현 정부에 국민들이 가장 원하는 것은 부패척결입니다. 우리 사회에 각종 비리들이 ...
2,23,2017-08-19,2017-09-03,0,0.0,미래,제2의 개성공단,"만일 하시는 대통령님 및 각 부처 장관님,주무관님들 안녕하세요!!\n전남 목포에서 ..."
3,24,2017-08-19,2017-08-26,0,53.0,일자리,공공기관 무조건적인 정규직전환을 반대합니다.,현정부에서 정규직 일자리를 늘리는 것에 찬성합니다. 그런데 공공기관 비정규직들은 인...
4,25,2017-08-19,2017-09-03,0,0.0,미래,제2의 개성공단,"만일 하시는 대통령님 및 각 부처 장관님,주무관님들 안녕하세요!!\n전남 목포에서 ..."

## 결측치가 있는지 널 값을 세어본다.

In [10]:
petitions.isnull().sum()

article_id      0
start           0
end             0
answered        0
votes         192
category        0
title           0
content         1
dtype: int64

In [11]:
petitions = petitions.loc[petitions['end'] >= '2018-03-01']
petitions.shape

(58127, 8)

## 투표수 결측치 데이터프레임 생성

In [12]:
petition_votes_null = petitions.loc[petitions['votes'].isnull()]
petition_votes_null.shape

(72, 8)

In [13]:
petition_votes_null.head()

,article_id,start,end,answered,votes,category,title,content
101795,121399,2018-01-30,2018-03-01,0,NaN,육아/교육,대학원생의 인권을 되찾아 주세요,대학원 학생들좀 보호해 주십시오.\n-학생에게 할당된 인건비 횡령하는 교수님들 너무...
102638,122512,2018-01-30,2018-03-01,0,NaN,육아/교육,초등학교 교사들에게 adhd등의 특수아동에 대한 기본교육이수를 의무화 해주세요.,현재 우리 초등학교에는 수많은 adhd 아이들이 있습니다.\n하지만 담임선생님들중에...
103223,123229,2018-01-31,2018-03-02,0,NaN,육아/교육,미혼모 아이아빠를 꼭 찾아서 같이 책임질수 있게 해주세요,이번에 신생아 유기사건을 보고 맘이 참 아픕니다\n이런일이 일어나지 않도록 미리 ...
103417,124037,2018-01-31,2018-03-02,0,NaN,육아/교육,아동 관련법 강화 부탁드립니다.,"말 그대로 아동학대, 방치, 기타 등등 모든 아동들을 지킬 수 있는 국가시스템을 개..."
103706,124354,2018-02-01,2018-03-03,0,NaN,육아/교육,발달지연 바우처 증가와 통합어린이집 증설,안녕하세요.\n저는 김포시에 살고있는 자폐스팩트럼을 가진 5살 아이의 엄마입니다.\...

In [14]:
petition_votes_null.tail()

,article_id,start,end,answered,votes,category,title,content
152461,183973,2018-04-03,2018-05-03,0,NaN,육아/교육,김상곤 교육부총리의 해임을 청원합니다.,지금 현재 고1 학생을 둔 학부모입니다.\n2018년 현재 대한민국 대입정책은 유사...
156625,190975,2018-04-08,2018-05-08,0,NaN,육아/교육,"<보육교사의 호소> 저출산, 아동학대, 모든것은 하나로 이어져있습니다.",안녕하세요 부천 국공립 어린이집에서 9년째 근무하고 있는 보육교사입니다. 저는 보육...
158545,194252,2018-04-10,2018-05-10,0,NaN,육아/교육,아동당뇨 자동체크기허용,어제 방송에서 아동당뇨 자동체크기. 인슐린자동주입기 에대한 방송이나오더라구요 미국에...
159000,195019,2018-04-11,2018-05-11,0,NaN,육아/교육,스마트폰 관련 제한,요즘 아이들 스마트폰의 유해 컨텐츠에 노출되어 걱정입니다\n학생들이 스마트폰을 보며...
159083,195195,2018-04-11,2018-05-11,0,NaN,육아/교육,김상곤 교육부 장관 사퇴,현재 수시가 대입에서 대부분을 차지하고 있음에도 경쟁률이 큰 이 마당에 수시에서 수...

### 투표수에 결측치가 없는 데이터프레임 생성

In [15]:
petition_votes_notnull = petitions.loc[petitions['votes'].notnull()]
petition_votes_notnull.shape

(58055, 8)

In [16]:
import re
from konlpy.tag import Twitter
t = Twitter()

def preprocessing(text):
    text = str(text)
    # 개행문자 제거
    text = re.sub('\\\\n', ' ', text)
    #text = t.pos(text, norm=True, stem=True)
    return text

In [17]:
pre_text = preprocessing(petition_votes_notnull['content'])
pre_text[:8]

'101644  '

In [18]:
# 참고 : https://gist.github.com/yong27/7869662
# http://www.racketracer.com/2016/07/06/pandas-in-parallel/
from multiprocessing import Pool
import numpy as np

def _apply_df(args):
    df, func, kwargs = args
    return df.apply(func, **kwargs)

def apply_by_multiprocessing(df, func, **kwargs):
    # 키워드 항목 중 workers 파라메터를 꺼냄
    workers = kwargs.pop('workers')
    # 위에서 가져온 workers 수로 프로세스 풀을 정의
    pool = Pool(processes=workers)
    # 실행할 함수와 데이터프레임을 워커의 수 만큼 나눠 작업
    result = pool.map(_apply_df, [(d, func, kwargs)
            for d in np.array_split(df, workers)])
    pool.close()
    # 작업 결과를 합쳐서 반환
    return pd.concat(list(result))

In [19]:
%time votes_notnull_content = apply_by_multiprocessing(\
    petition_votes_notnull['content'], preprocessing, workers=4)

CPU times: user 544 ms, sys: 1.03 s, total: 1.57 s
Wall time: 1.63 s

In [20]:
#%time votes_notnull_content = petition_votes_notnull['content'].apply(preprocessing)

In [21]:
votes_notnull_content[:3]

101644     한마디로 똥묻은개가 생각납니다. 검사옷을 입을 자격이 없는 자입니다. 파면 시켜주십시요
101645    일제시대때 외국에 나가 살다가 현재는 3~4대까지 이어져온 분중에 대한민국 국민으로...
101646    6억이상에 대하여 종부세 매겨야  경제민주화 입니다ㆍ 어떤 국회의원은 12억 이상 ...
Name: content, dtype: object

In [22]:
#%time votes_null_content = petition_votes_null['content'].apply(preprocessing)
%time votes_null_content = apply_by_multiprocessing(\
    petition_votes_null['content'], preprocessing, workers=4)

CPU times: user 16.8 ms, sys: 41.9 ms, total: 58.7 ms
Wall time: 99.2 ms

In [23]:
votes_null_content[:3]

101795    대학원 학생들좀 보호해 주십시오. -학생에게 할당된 인건비 횡령하는 교수님들 너무나...
102638    현재 우리 초등학교에는 수많은 adhd 아이들이 있습니다. 하지만 담임선생님들중에는...
103223    이번에 신생아 유기사건을 보고 맘이  참 아픕니다 이런일이 일어나지 않도록 미리 예...
Name: content, dtype: object

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline

vectorizer = CountVectorizer(analyzer = 'word', 
                             tokenizer = None,
                             preprocessor = None, 
                             stop_words = None, 
                             min_df = 2,
                             ngram_range=(1, 3),
                             max_features = 1000
                            )
vectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=1000, min_df=2,
        ngram_range=(1, 3), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [25]:
pipeline = Pipeline([
    ('vect', vectorizer),
])

In [26]:
%time train_data_features = pipeline.fit_transform(votes_notnull_content)
train_data_features.shape

CPU times: user 1min 12s, sys: 2.18 s, total: 1min 14s
Wall time: 1min 14s

(58055, 1000)

In [27]:
%time test_data_features = pipeline.fit_transform(votes_null_content)
test_data_features.shape

CPU times: user 1.5 s, sys: 185 ms, total: 1.68 s
Wall time: 1.68 s

(72, 1000)

In [28]:
vocab = vectorizer.get_feature_names()
print(len(vocab))
vocab[:10]

1000

['12년의', '20', '2005년', '2018년', '2019학년도', '2년', '30', '3학년', '50', '80']

In [29]:
# 벡터화 된 피처를 확인해 봄
# Bag of words 에 몇 개의 단어가 들어있는지 확인
dist = np.sum(test_data_features, axis=0)
    
for tag, count in zip(vocab, dist):
    print(count, tag)
    
pd.DataFrame(dist, columns=vocab)

[[ 3  4  3  3  4  3  6  5  6  3  6  3  3  3 21  5  3  3  5  7  3  5  3  4
   4  9 22  5  5  3  5 14  3  3  4  4 20  9 18  5  3 25  5  3  5  5  4 12
   4  5  3  5  4  3 13  3  3  4  9  5  5  3 13  3 13  3  4  4  6  3  8  3
   5  4 17  4  6  3 13  4  3  5  4 12 10  9  3  3  3 15  6  3  6  6  4  4
   6  3  3  3  7  7  4 12  8 11 10  9  9  3  3 31  4  3  7  7  7  5  3  3
   5  3  3  3  3  5  6  3  9  3  5  5  3  3  3  6  3  4  3 11  4  5  4 20
   5  6  3  9  4  3  3  3  4  3  3  3  3  3 17  9  5  3  8  3  7  3  9  4
   3 14  3  3  3  5  7  3  5  3  4  3  9  4  9  7 15 11  3  4 17  3 12  3
   5  4  3  4  4  4  4  3 12  3  6  4  5  6 20  3  3  5  4  4  6  7 10  4
  22 14 30  3  4  5  3  3  7  5 16 27 23  5  4 12  5  3  3  3  4  3  4  4
   3  5  3  9  3 22  6 29  3  5  5  5  9  3  3  4  4  7  5 23  3  3  8  8
   3  4  3  3 11  5  5  5  3  3  7  3 10  4  5  3  3  3  7  3  3  3  5  9
   5  3  3  7  3  5  8  3  9  4  3  4  3  3  7  3  7  4  3  5  4  7  3  3
   3  3  6  3  3  4  3  4  5  6  4  6  4  3  4  4  3  3  3  4  3  3  6  4
   4  4  5  3  5  5  3  6  7  4  5  3 30  3  5  4  6  3  3  4  3  5  3  8
   4  3  3  4  3  6 33 11  3 12  3  3 27  3  6  3  3  8  3  8  3  4  8  4
   7  3  3  3  3  8  3  3  3  3  5  4  4  4  5  3  4  4  3  3  5  6  3  8
   3 18  4  4 17  6  4  4  8  7  8  7  8 11  8  6 18  7 17  8  5  4  4  4
   3  3 11  6  4  3  4  4 18  6  4 10  5 10  3  3  9  6  3  6  5 12 17  3
  36  4  5  6  4  5  4  4  3  5  3  3  3  3  5  5 12  3  4  9  3 40  4  4
   3  4 13  4  3  3  4 16  6  3  2  3  2  3  2  2  2 10  3  2  2  2  2  2
   2  2  7  2  2  2  4  2  7  2  6  2 10  5  2  2  4  7  5  3  6  3  2  2
   4  2  2  2  2  5  2  2  8  3  2  2  2  2  2  2  4 30  2  2  2  2  2  2
   2  2  2  2 20  4  2  8  2  4  2  2  2  4  4  2  2  3  9  7  5 21 24  2
   2  2  2 17  2  3  2  2  2  2  9  5  8  3  2  2  2 10  2  2  3  3  2  6
   2  3  8 10  2  2  2  2  7  2  2  2  2  2  5  2  6  2  4  3  2  2  2  2
   2  3  2  2  2  2  2  2  2  2  7 11  2  6  6  3  2  2  2  2 15  7  5  3
   3  3 23  8  6  3  5  4 80  3  9 10  8  5  4 13  5 78  4  3  5  4  5  3
   4  3  4  6  3  7  4  5  9  6  6  4  3  3  3  3  4  4  3 36  5  5 10  3
   6  6  3  4  3  3  3  5  3  8  3  4  3  4  4 26  3  3  4  3  4  6 16  4
   4  3  7  8  5 13  3  3 16  6  4 16  3  4  3  4  3  3  3  4 12 12  3  3
   3  5  7 13  3  4  3  7  4 13  4  7  6  3 19  6  4  3  3  3  4  3 13  4
   3  4  3  4  4  4  3  9  5  3 20  4  3  3  6  4  3  5  6  3  3  4  3  5
   3  7  6  5  9  3  9  9  3  5  3  8  4  4 20  5  3  4 34  6  4  3  3  5
   6  9  9  3  9  3  4  9 28 20  8  4  9  3  3  2  2  2  5 12  4  9  3 10
  10  5  2  4  3 24  2  9 12  4  3  8 24 18  2 26  2 40  2 17  2  4  3  3
   5  3  4  5  2  7  4 16  7  9  3  2  3  5  2  6  2  2  7  5  2  2  2  2
   2  2  2  2  2  2  2  2  4 67  2  2  2  3  2  3  2  2  8 10  2  2 10  3
   2  2  2  2  3  6  2 10  4  2  2  2  2  2  2  2  2  2  2  4  2  2  2  2
   3  2  2  3  4  2  3  2  2  2  2  2  3  2  2  5  2  2  2  2  2  2  2  3
   2  2  2  3 29  5  2  2  2  2  2  2  2  2  2  4  4  2  2  2  2  3  2  2
   3  4  2  3  3  2  2  2  4  2  2  2  2  4  3  2]] 12년의

,12년의,20,2005년,2018년,2019학년도,2년,30,3학년,50,80,...,후의 현장은,후의 현장은 어떨까요,훨씬,휴가,휴게시간,휴게시간 포함한,휴게시간 포함한 한시간,희망을,힘든,힘든 상황
0,3,4,3,3,4,3,6,5,6,3,...,2,2,4,2,2,2,2,4,3,2

In [30]:
# 각 row에서 전체 단어가방에 있는 어휘에서 등장하는 단어에 대한 one-hot-vector
pd.DataFrame(test_data_features[:10].toarray(), columns=vocab).head()

,12년의,20,2005년,2018년,2019학년도,2년,30,3학년,50,80,...,후의 현장은,후의 현장은 어떨까요,훨씬,휴가,휴게시간,휴게시간 포함한,휴게시간 포함한 한시간,희망을,힘든,힘든 상황
0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
X_train = train_data_features
X_train.shape

(58055, 1000)

In [32]:
X_test = test_data_features
X_test.shape

(72, 1000)

In [33]:
y_train = petition_votes_notnull['votes']
y_train.shape

(58055,)

In [34]:
X_test

<72x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 4213 stored elements in Compressed Sparse Row format>

In [35]:
X_test[2][:100]

<1x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 26 stored elements in Compressed Sparse Row format>

# DecisionTree로 투표수 예측

In [36]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(max_depth=5, random_state=2015)

In [37]:
%time dt = dt.fit(X_train, y_train)

CPU times: user 214 ms, sys: 14.5 ms, total: 229 ms
Wall time: 228 ms

In [38]:
dt_result = dt.predict(X_test)
dt_result

array([ 126.2448916 ,  126.2448916 ,  126.2448916 ,  191.19178082,
        126.2448916 ,  126.2448916 ,  892.35416667,  126.2448916 ,
        126.2448916 ,  126.2448916 ,  126.2448916 ,  126.2448916 ,
        126.2448916 ,  126.2448916 ,  126.2448916 ,  126.2448916 ,
        126.2448916 ,  126.2448916 ,  126.2448916 ,  126.2448916 ,
        126.2448916 ,  126.2448916 ,  126.2448916 , 5508.94230769,
        126.2448916 ,  126.2448916 ,  126.2448916 ,  126.2448916 ,
        126.2448916 ,  126.2448916 ,  126.2448916 ,  126.2448916 ,
        126.2448916 ,  126.2448916 ,  126.2448916 ,  126.2448916 ,
        126.2448916 ,  126.2448916 ,  126.2448916 ,  126.2448916 ,
        126.2448916 ,  126.2448916 ,  126.2448916 ,  126.2448916 ,
        126.2448916 ,  126.2448916 ,  126.2448916 ,  126.2448916 ,
        126.2448916 ,  126.2448916 ,  126.2448916 ,  126.2448916 ,
        126.2448916 ,  126.2448916 ,  126.2448916 ,  126.2448916 ,
        126.2448916 ,  126.2448916 ,  126.2448916 ,  126.2448916 ,
        126.2448916 ,  126.2448916 ,  126.2448916 ,  126.2448916 ,
        126.2448916 ,  126.2448916 ,  126.2448916 ,  126.2448916 ,
        126.2448916 ,  126.2448916 ,  126.2448916 ,  126.2448916 ])

In [39]:
# brew install graphviz
# conda install graphviz
from sklearn.tree import export_graphviz
import graphviz

export_graphviz(dt, out_file = "decision-tree.dot")

with open("decision-tree.dot") as f:
    dot_graph = f.read()

In [40]:
graphviz.Source(dot_graph)

# RamdomForest로 투표수 예측

In [41]:
from sklearn.ensemble import RandomForestRegressor

forest = RandomForestRegressor(
    n_estimators = 100, n_jobs = -1, random_state=2018)
forest

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
           oob_score=False, random_state=2018, verbose=0, warm_start=False)

In [42]:
%time forest = forest.fit(X_train, y_train)

CPU times: user 2h 8min 34s, sys: 21.3 s, total: 2h 8min 55s
Wall time: 33min 49s

In [43]:
result = forest.predict(X_test)
result

array([8.33543764e+02, 3.73650000e+02, 3.27523333e+01, 1.71820000e+02,
       1.20465667e+03, 4.57421069e+02, 2.71977000e+03, 5.50640000e+02,
       9.31071667e+02, 3.76656226e+01, 1.69198114e+03, 2.48379800e+03,
       5.49187700e+03, 1.67360000e+01, 3.05981333e+02, 2.21503500e+03,
       2.59410473e+01, 6.01325974e+00, 2.97423000e+03, 7.87490000e+02,
       3.87770000e+02, 3.60667500e+02, 7.79950000e+01, 8.32250000e+02,
       1.46758333e+01, 6.21753333e+02, 1.00239000e+03, 8.95315909e+01,
       7.71150000e+01, 3.09955333e+02, 1.32365167e+03, 1.83392500e+03,
       1.22069385e+03, 1.86889333e+03, 2.51380000e+02, 4.10192300e+04,
       4.21300000e+01, 5.60787793e+01, 3.48260500e+04, 4.62200000e+01,
       1.61211625e+03, 4.50866667e+01, 4.05902033e+01, 2.21478500e+03,
       5.19892273e+01, 1.34570700e+04, 1.67775000e+02, 6.45500000e+00,
       9.11960714e+02, 2.10011000e+02, 1.71694600e+04, 2.64816667e+01,
       1.18635592e+01, 2.13265820e+01, 4.60911111e+00, 1.26712500e+02,
       1.10897750e+04, 4.22315000e+02, 7.86842000e+02, 1.93637500e+02,
       7.93581381e+02, 6.30457931e+01, 9.80385714e+01, 4.79545688e+01,
       6.78519777e+01, 1.04072000e+03, 3.08160000e+02, 1.84623000e+03,
       1.54820500e+03, 8.29000000e+00, 8.33700490e+01, 2.13480000e+02])

In [44]:
result.shape

(72,)

In [45]:
# 결과값만 따로 모아 본다.
output = pd.DataFrame(data={'article_id':petition_votes_null['article_id'], 'votes':result})
output.head()

        article_id        votes
101795      121399   833.543764
102638      122512   373.650000
103223      123229    32.752333
103417      124037   171.820000
103706      124354  1204.656667

In [46]:
# 어떤 데이터의 투표수인지 보기 위해 article_id로 데이터를 불러온다.
petition_votes_null.loc[petition_votes_null['article_id'] == 121399]

,article_id,start,end,answered,votes,category,title,content
101795,121399,2018-01-30,2018-03-01,0,NaN,육아/교육,대학원생의 인권을 되찾아 주세요,대학원 학생들좀 보호해 주십시오.\n-학생에게 할당된 인건비 횡령하는 교수님들 너무...

In [47]:
# 투표수를 결측치에 넣어준다.
petition_votes_null['votes_predict'] = result
petition_votes_null['votes_predict_dt'] = dt_result

In [48]:
petition_votes_null

,article_id,start,end,answered,votes,category,title,content,votes_predict,votes_predict_dt
101795,121399,2018-01-30,2018-03-01,0,NaN,육아/교육,대학원생의 인권을 되찾아 주세요,대학원 학생들좀 보호해 주십시오.\n-학생에게 할당된 인건비 횡령하는 교수님들 너무...,833.543764,126.244892
102638,122512,2018-01-30,2018-03-01,0,NaN,육아/교육,초등학교 교사들에게 adhd등의 특수아동에 대한 기본교육이수를 의무화 해주세요.,현재 우리 초등학교에는 수많은 adhd 아이들이 있습니다.\n하지만 담임선생님들중에...,373.650000,126.244892
103223,123229,2018-01-31,2018-03-02,0,NaN,육아/교육,미혼모 아이아빠를 꼭 찾아서 같이 책임질수 있게 해주세요,이번에 신생아 유기사건을 보고 맘이 참 아픕니다\n이런일이 일어나지 않도록 미리 ...,32.752333,126.244892
103417,124037,2018-01-31,2018-03-02,0,NaN,육아/교육,아동 관련법 강화 부탁드립니다.,"말 그대로 아동학대, 방치, 기타 등등 모든 아동들을 지킬 수 있는 국가시스템을 개...",171.820000,191.191781
103706,124354,2018-02-01,2018-03-03,0,NaN,육아/교육,발달지연 바우처 증가와 통합어린이집 증설,안녕하세요.\n저는 김포시에 살고있는 자폐스팩트럼을 가진 5살 아이의 엄마입니다.\...,1204.656667,126.244892
106540,127795,2018-02-05,2018-03-07,0,NaN,육아/교육,역사교과서 개정안 반대,6.25전쟁\n김일성이라는 독재자가 자유민주주의국가인 한국을 공산화하기 위해 벌여 ...,457.421069,126.244892
109893,131763,2018-02-07,2018-03-09,0,NaN,육아/교육,고등학교 학교생활기록부(학생부) 개편안 무효화를 청원합니다.,"안녕하십니까, 저희는 올해 고등학생이 되는 청소년들입니다.\n얼마 전 교육부에서 고...",2719.770000,892.354167
114530,137376,2018-02-12,2018-03-14,0,NaN,육아/교육,어린이집 교사 처우 개선 할 수 있게 부탁 드립니다.,수고 많으십니다.\n항상 열린 마음으로 국민들의 이야기를 들어 주셔서 먼저 감사드립...,550.640000,126.244892
117376,140679,2018-02-16,2018-03-18,0,NaN,육아/교육,학교 두발규정을 없애주세요.,친애하는 문재인 대통령님. 학교에서는 약 한달에 한번씩 두발검사를 합니다. 그러나 ...,931.071667,126.244892
117476,140799,2018-02-16,2018-03-18,0,NaN,육아/교육,유치원은 왜 현금결제만?,"이번에 유치원 전쟁을 치룬 엄마입니다. 입학만 되면 감사한 이런분위기에 놀라고, ...",37.665623,126.244892
117607,140950,2018-02-17,2018-03-19,0,NaN,육아/교육,영양사가 왜 영양'교사'로 임용되는 것 입니까,"교사라는 호칭이 붙었으니, 담임, 생활지도, 수업, 시험문제 출제+채점, 행정업무 ...",1691.981136,126.244892
121524,145507,2018-02-21,2018-03-23,0,NaN,육아/교육,국민의 세금으로 국가가 설립해 운영하는 국립대학교 학사지원과 수강신청 담당자의 태도...,"""이번에 수강신청 하려고 하는 학생인데 10시 12분까지 10분 넘게 서버가 다운되...",2483.798000,126.244892
122432,146538,2018-02-22,2018-03-24,0,NaN,육아/교육,초등 돌봄에 대한 원망,이번에 초등학교 가는 딸아이있는 맞벌이하는 엄마 입니다.\n저희애는 이번에 초등 돌...,5491.877000,126.244892
127136,152131,2018-02-26,2018-03-28,0,NaN,육아/교육,방과후 수업 의무화 반대운동,방과후 수업을 의무화하는 것은 자유민주주의에 벗어나는 것입니다 이것은 학생의 자유...,16.736000,126.244892
127746,152840,2018-02-27,2018-03-29,0,NaN,육아/교육,"수능 수학에서 기하,벡터를 뺀 망국적인 결정을 취소하고 김상곤 교육부를 경질시켜 주세요","교육부가 4차산업혁명시대 국가경쟁력, 과학선진국으로 가는 교육을 망치는 제1의 ...",305.981333,126.244892
128254,153425,2018-02-27,2018-03-29,0,NaN,육아/교육,<미투> 교원평가제와 교원성과급제 폐지를 교육부에 강력히 요청합니다.,"I\nMB 정부의 이주호(안병만 교육부장관시절 교육부 제1차관, 이후 교육부장관) ...",2215.035000,126.244892
128636,153886,2018-02-28,2018-03-30,0,NaN,육아/교육,교육부와청와대는 총신대사태 보고만계실겁니까,총신대사태를바라보며 정부와 교육부는 뮐하고계십니까 학생들이 입학도 졸업도 개강도 못...,25.941047,126.244892
131279,156989,2018-03-03,2018-04-02,0,NaN,육아/교육,레인보우합창단을 돈벌이로 이용하는 한국다문화센터 조사해 주세요!!,다문화 가정 자녀를 지원한다는 명목으로 사리사욕을 채우는 한국다문화센터 비용 집행내...,6.013260,126.244892
131940,157825,2018-03-04,2018-04-03,0,NaN,육아/교육,전남 순천시 해룡면 신대지구 어린이집 입소대기 해소 해주세요.,안녕하세요.\n저는 전남 순천시 신대지구에 살고 맞벌이를 하고 있는 18개월 아이 ...,2974.230000,126.244892
134252,160682,2018-03-07,2018-04-06,0,NaN,육아/교육,고용노동부 법정의무교육 교육비 삭감 민원,안녕하세요~\n저희는 사업주위탁 훈련기관의 영업대리점 입니다.\n제가 메일을 드리는...,787.490000,126.244892
134544,161069,2018-03-08,2018-04-07,0,NaN,육아/교육,민간 가정어린이집 운영자도 대한민국 국민 입니까?,국가사업인 어린이집 운영을 국가와 개인이 나누어 운영 한다면\n차별지원은 없어야 ...,387.770000,126.244892
134903,161509,2018-03-08,2018-04-07,0,NaN,육아/교육,중소기업 여성근로자의 육아휴직 제도...저희를 지켜주세요.,안녕하세요. 저는 60명 정도의 규모를 가진 중소기업에 5년동안 재직중인 여성 근로...,360.667500,126.244892
135142,161790,2018-03-08,2018-04-07,0,NaN,육아/교육,학생들의 인권도 보장해주세요 !,안녕하세요 저는 대한민국의 한 청소년입니다 제가 이렇게 글을 남기는 이유는 학생이라...,77.995000,126.244892
136466,163506,2018-03-11,2018-04-10,0,NaN,육아/교육,고등학교 생활기록부 변경 취소,안녕하세요 저는 올해 특성화고를 진학한 1학년 학생입니다 다름이 아니라 고등학교 생...,832.250000,5508.942308
136569,163637,2018-03-11,2018-04-10,0,NaN,육아/교육,중고등학교 여학생 교복을 편하게 만들어주세요,현재 여중생 자녀를 둔 학부모입니다.\n불편한 교복을 입고 하루종일 공부하고 활동에...,14.675833,126.244892
137003,164207,2018-03-11,2018-04-10,0,NaN,육아/교육,"여중생, 여고생의 교복에 대해 다시 한번 검토해주십시오.",안녕하십니까 . 저는 중학교에 재학중인 16살 학생입니다. 제가 이렇게 국민청원까지...,621.753333,126.244892
137318,164626,2018-03-12,2018-04-11,0,NaN,육아/교육,"초등, 중등학교 스마트폰 사용을 제한해 주세요. (특히 단톡방)",제목 그대로 입니다.\n아이들에게 다양한 기회를 빼앗는 스카트폰의 폐해에 대하여\n...,1002.390000,126.244892
137821,165248,2018-03-13,2018-04-12,0,NaN,육아/교육,초등학교생활에 엄마역활을 빼주세요,초등학교에 들어가면 저학년때부터 고학년까지\n엄마들이 학교에와서 역할을 해야한다고 ...,89.531591,126.244892
139689,167604,2018-03-16,2018-04-15,0,NaN,육아/교육,김상곤교육부 장관 해임해주세요!!!,고1을 둔 엄마입니다.학부모총회때 두툼한 안내책자를 주었습니다.아무리 내용을 봐도 ...,77.115000,126.244892
143382,172267,2018-03-22,2018-04-21,0,NaN,육아/교육,순천 신대지구 유치원,사립유치원의 갑질횡포.도와주세요\n내용\n6세 학부모입니다. 이번에 변경된 영어교육...,309.955333,126.244892
...,...,...,...,...,...,...,...,...,...,...
145664,175351,2018-03-25,2018-04-24,0,NaN,육아/교육,수시 줄이라니까 최저를 없애는 김상곤 교육부 장관 사퇴하세요.,전 국민 설문조사 한번 돌립시다. 수시가 응원받는지 정시가 응원받는지.\n강력한 드...,40.590203,126.244892
145730,175433,2018-03-25,2018-04-24,0,NaN,육아/교육,수능 최저기준 폐지에 강력하게 반대합니다,2019학년도 수능때부터 수능최저를 없애는 쪽으로 교육부가 일을 추진한다는 기사를 ...,2214.785000,126.244892
145828,175551,2018-03-26,2018-04-25,0,NaN,육아/교육,미세먼지 관련 임시휴교,"지금 통합대기지수가 260으로 솟구치고 있으나 초,중,고등학교 학생들이 중국발 미세...",51.989227,126.244892
145928,175663,2018-03-26,2018-04-25,0,NaN,육아/교육,"학생부종합전형 비중 축소 및 정시 비중 확대, 수시 수능최저등급 폐지 철회를 부탁드립니다","작년 5월 문재인 대통령께서 내세우셨던 교육 정책이 수시 비중 확대, 수능의 절대평...",13457.070000,126.244892
145945,175688,2018-03-26,2018-04-25,0,NaN,육아/교육,수시비중보다 정시비중을 높여야합니다,저는 일년전까지 직장생활을 하던 스물여섯살 늦깍이 수험생입니다. 고졸출신으로 사회...,167.775000,126.244892
145969,175720,2018-03-26,2018-04-25,0,NaN,육아/교육,수능최저폐지 철회및 교육감사퇴,기준도 명확하지 않은 수시에 유일하게 실력미달자를 걸러줄수있는 수시최저를 없앤다는것...,6.455000,126.244892
146125,175911,2018-03-26,2018-04-25,0,NaN,육아/교육,수능 최저 폐지 및 정시 확대를 요구합니다.,지금 대학교에 재학 중인 학생입니다. 요즘 수능 최저 폐지 때문에 말이 많습니다....,911.960714,126.244892
146220,176037,2018-03-26,2018-04-25,0,NaN,육아/교육,수능최저 폐지 반대,고3학부모입니다. '수능최저 폐지 ' 를 듣고 너무 당황했습니다. 그것도 2019...,210.011000,126.244892
146420,176293,2018-03-26,2018-04-25,0,NaN,육아/교육,수능 최저 기준 폐지를 반대합니다.,현 입시제도에 가장 영향을 많이 받고 민감하게 반응할 수밖에 없는 고3 학생입니다....,17169.460000,126.244892
147168,177261,2018-03-27,2018-04-26,0,NaN,육아/교육,올해 수능부터 정시를 늘려주세요,존경하고 사랑하는 문재인대통령님이하 많은 분들의 수고에 감사의 인사를 드립니다\n현...,26.481667,126.244892
147746,178003,2018-03-27,2018-04-26,0,NaN,육아/교육,전국 초.중.고등학교에 공기청정기 설치 의무화실시,요즘처럼 대기질 상태가 심각하게 나쁠때 우리 어린자녀들이 공부하는 학교에 공기청정기...,11.863559,126.244892
148347,178762,2018-03-28,2018-04-27,0,NaN,육아/교육,공정한 대입 ..수시 축소 정시 확대,아이들의 미래가 달린 대학입시입니다.\n누군가의 낡은 소신으로 밀어붙일 문제가 아닙...,21.326582,126.244892
148728,179271,2018-03-29,2018-04-28,0,NaN,육아/교육,수능최저폐지 반대 및 학생부종합전형 축소를 원합니다,수능최저폐지 반대 및 학생부종합전형 축소를 원합니다,4.609111,126.244892
149538,180259,2018-03-29,2018-04-28,0,NaN,육아/교육,수시 폐지! 수능 2회 실시 청원 합니다.,학종부전형을 비롯한 모든 수시 폐지와 수능 2회 실시를 청원합니다.\n과거제도입이 ...,126.712500,126.244892
149636,180370,2018-03-30,2018-04-29,0,NaN,육아/교육,수시 최저 폐지 반대! 모두의 의견도 들어주세요.,안녕하세요. 현재 몸이 많이 안좋아 부득이하게 학교를 자퇴하고 검정고시를 본 청소년...,11089.775000,126.244892
149877,180668,2018-03-30,2018-04-29,0,NaN,육아/교육,4차 산업혁명 시대에 맞게 학교 우유급식 신청을 앱이나 컴퓨터로 간편하게 하고 가정...,4차 산업혁명의 시대에 학교에서 수십 년 동안 가장 변하지 않는 것이 있다면 우유급...,422.315000,126.244892
149940,180741,2018-03-30,2018-04-29,0,NaN,육아/교육,대학원생 인건비 문제 해결해주세요,"1. 인건비 계좌 관리\n학생들 각자, 연구과제 인건비를 지급받을 계좌를 가지고 있...",786.842000,126.244892
150083,180917,2018-03-30,2018-04-29,0,NaN,육아/교육,다산신도시 진건2초유3의 중투위통과를 요청합니다,"제목 : 다산 진건 2초, 유3 의 중투위 통과를 요청합니다.\n현재 다산 초등학교...",193.637500,126.244892
150358,181276,2018-03-30,2018-04-29,0,NaN,육아/교육,2019학년도부터 정시확대 요구합니다,올해 수능을 준비하는 학생입니다.지금 2020학년도부터 정시확대를 하도록 교육부가 ...,793.581381,126.244892
150892,181919,2018-03-31,2018-04-30,0,NaN,육아/교육,"수시 수능 최저등급폐지 반대, 정시 대폭확대 희망합니다.","천하가 다 아는 불공정한 학종, 그들만을 위한 잔치,\n거기다 최저등급폐지까지 하...",63.045793,126.244892
151370,182544,2018-04-01,2018-05-01,0,NaN,육아/교육,홍신학원 법정부담금 24억 이자 붙혀서 받아내주십시오.,존경하는 대통령님\n대통령님이 만드시고자 하시는 공정하고 정의로운 세상을 만들기 위...,98.038571,126.244892
151641,182890,2018-04-01,2018-05-01,0,NaN,육아/교육,수능 정시 비율 확대,지금 수능 비율이 거의 20~30% 간당간당합니다.\n또 여기서 수능이 폐지 된다는...,47.954569,126.244892
151744,183021,2018-04-02,2018-05-02,0,NaN,육아/교육,월요일을 주말로해주세요,갈수록 힘들어지는 나날과 휴식이 더욱이 중요해지는 이날에 5일나가고2일쉬기란 다음날...,67.851978,126.244892
152183,183587,2018-04-02,2018-05-02,0,NaN,육아/교육,아이들을 위해서 어린이집 증설 보육교사 처우개선이 필요합니다.,저출산 문제가 심화되고 있습니다.\n이유는 아이들을 나을 경제적 여건도 이들을 나아...,1040.720000,126.244892
152403,183882,2018-04-03,2018-05-03,0,NaN,육아/교육,수능 정시 확대 요청합니다,문재인대통령과 김상조 씨! 이 청원 꼭 봐주세요\n저는 학창시절을 몇년전에 겪은 대...,308.160000,126.244892
152461,183973,2018-04-03,2018-05-03,0,NaN,육아/교육,김상곤 교육부총리의 해임을 청원합니다.,지금 현재 고1 학생을 둔 학부모입니다.\n2018년 현재 대한민국 대입정책은 유사...,1846.230000,126.244892
156625,190975,2018-04-08,2018-05-08,0,NaN,육아/교육,"<보육교사의 호소> 저출산, 아동학대, 모든것은 하나로 이어져있습니다.",안녕하세요 부천 국공립 어린이집에서 9년째 근무하고 있는 보육교사입니다. 저는 보육...,1548.205000,126.244892
158545,194252,2018-04-10,2018-05-10,0,NaN,육아/교육,아동당뇨 자동체크기허용,어제 방송에서 아동당뇨 자동체크기. 인슐린자동주입기 에대한 방송이나오더라구요 미국에...,8.290000,126.244892
159000,195019,2018-04-11,2018-05-11,0,NaN,육아/교육,스마트폰 관련 제한,요즘 아이들 스마트폰의 유해 컨텐츠에 노출되어 걱정입니다\n학생들이 스마트폰을 보며...,83.370049,126.244892
159083,195195,2018-04-11,2018-05-11,0,NaN,육아/교육,김상곤 교육부 장관 사퇴,현재 수시가 대입에서 대부분을 차지하고 있음에도 경쟁률이 큰 이 마당에 수시에서 수...,213.480000,126.244892

In [49]:
petitions_notnull = pd.read_csv('data/petition.csv')

In [50]:
# 원래 데이터의 투표수를 본다.
petitions_notnull.loc[petitions_notnull['article_id'] == 183021]

,article_id,start,end,answered,votes,category,title,content
151744,183021,2018-04-02,2018-05-02,0,155,육아/교육,월요일을 주말로해주세요,갈수록 힘들어지는 나날과 휴식이 더욱이 중요해지는 이날에 5일나가고2일쉬기란 다음날...

In [51]:
petitions_notnull.loc[petitions_notnull['article_id'] == 181276]

,article_id,start,end,answered,votes,category,title,content
150358,181276,2018-03-30,2018-04-29,0,1936,육아/교육,2019학년도부터 정시확대 요구합니다,올해 수능을 준비하는 학생입니다.지금 2020학년도부터 정시확대를 하도록 교육부가 ...

In [52]:
# 원래 데이터와 예측한 수의 차이가 어느정도인지 본다.
petition_votes_null['votes'] = petitions_notnull['votes']
petition_votes_null['votes_diff'] = petitions_notnull['votes'] - petition_votes_null['votes_predict'] 
petition_votes_null['votes_diff_dt'] = petitions_notnull['votes'] - petition_votes_null['votes_predict_dt']

In [53]:
petition_votes_null

,article_id,start,end,answered,votes,category,title,content,votes_predict,votes_predict_dt,votes_diff,votes_diff_dt
101795,121399,2018-01-30,2018-03-01,0,79,육아/교육,대학원생의 인권을 되찾아 주세요,대학원 학생들좀 보호해 주십시오.\n-학생에게 할당된 인건비 횡령하는 교수님들 너무...,833.543764,126.244892,-754.543764,-47.244892
102638,122512,2018-01-30,2018-03-01,0,187,육아/교육,초등학교 교사들에게 adhd등의 특수아동에 대한 기본교육이수를 의무화 해주세요.,현재 우리 초등학교에는 수많은 adhd 아이들이 있습니다.\n하지만 담임선생님들중에...,373.650000,126.244892,-186.650000,60.755108
103223,123229,2018-01-31,2018-03-02,0,1496,육아/교육,미혼모 아이아빠를 꼭 찾아서 같이 책임질수 있게 해주세요,이번에 신생아 유기사건을 보고 맘이 참 아픕니다\n이런일이 일어나지 않도록 미리 ...,32.752333,126.244892,1463.247667,1369.755108
103417,124037,2018-01-31,2018-03-02,0,72,육아/교육,아동 관련법 강화 부탁드립니다.,"말 그대로 아동학대, 방치, 기타 등등 모든 아동들을 지킬 수 있는 국가시스템을 개...",171.820000,191.191781,-99.820000,-119.191781
103706,124354,2018-02-01,2018-03-03,0,82,육아/교육,발달지연 바우처 증가와 통합어린이집 증설,안녕하세요.\n저는 김포시에 살고있는 자폐스팩트럼을 가진 5살 아이의 엄마입니다.\...,1204.656667,126.244892,-1122.656667,-44.244892
106540,127795,2018-02-05,2018-03-07,0,63,육아/교육,역사교과서 개정안 반대,6.25전쟁\n김일성이라는 독재자가 자유민주주의국가인 한국을 공산화하기 위해 벌여 ...,457.421069,126.244892,-394.421069,-63.244892
109893,131763,2018-02-07,2018-03-09,0,1636,육아/교육,고등학교 학교생활기록부(학생부) 개편안 무효화를 청원합니다.,"안녕하십니까, 저희는 올해 고등학생이 되는 청소년들입니다.\n얼마 전 교육부에서 고...",2719.770000,892.354167,-1083.770000,743.645833
114530,137376,2018-02-12,2018-03-14,0,91,육아/교육,어린이집 교사 처우 개선 할 수 있게 부탁 드립니다.,수고 많으십니다.\n항상 열린 마음으로 국민들의 이야기를 들어 주셔서 먼저 감사드립...,550.640000,126.244892,-459.640000,-35.244892
117376,140679,2018-02-16,2018-03-18,0,144,육아/교육,학교 두발규정을 없애주세요.,친애하는 문재인 대통령님. 학교에서는 약 한달에 한번씩 두발검사를 합니다. 그러나 ...,931.071667,126.244892,-787.071667,17.755108
117476,140799,2018-02-16,2018-03-18,0,307,육아/교육,유치원은 왜 현금결제만?,"이번에 유치원 전쟁을 치룬 엄마입니다. 입학만 되면 감사한 이런분위기에 놀라고, ...",37.665623,126.244892,269.334377,180.755108
117607,140950,2018-02-17,2018-03-19,0,2246,육아/교육,영양사가 왜 영양'교사'로 임용되는 것 입니까,"교사라는 호칭이 붙었으니, 담임, 생활지도, 수업, 시험문제 출제+채점, 행정업무 ...",1691.981136,126.244892,554.018864,2119.755108
121524,145507,2018-02-21,2018-03-23,0,119,육아/교육,국민의 세금으로 국가가 설립해 운영하는 국립대학교 학사지원과 수강신청 담당자의 태도...,"""이번에 수강신청 하려고 하는 학생인데 10시 12분까지 10분 넘게 서버가 다운되...",2483.798000,126.244892,-2364.798000,-7.244892
122432,146538,2018-02-22,2018-03-24,0,84,육아/교육,초등 돌봄에 대한 원망,이번에 초등학교 가는 딸아이있는 맞벌이하는 엄마 입니다.\n저희애는 이번에 초등 돌...,5491.877000,126.244892,-5407.877000,-42.244892
127136,152131,2018-02-26,2018-03-28,0,4615,육아/교육,방과후 수업 의무화 반대운동,방과후 수업을 의무화하는 것은 자유민주주의에 벗어나는 것입니다 이것은 학생의 자유...,16.736000,126.244892,4598.264000,4488.755108
127746,152840,2018-02-27,2018-03-29,0,395,육아/교육,"수능 수학에서 기하,벡터를 뺀 망국적인 결정을 취소하고 김상곤 교육부를 경질시켜 주세요","교육부가 4차산업혁명시대 국가경쟁력, 과학선진국으로 가는 교육을 망치는 제1의 ...",305.981333,126.244892,89.018667,268.755108
128254,153425,2018-02-27,2018-03-29,0,112,육아/교육,<미투> 교원평가제와 교원성과급제 폐지를 교육부에 강력히 요청합니다.,"I\nMB 정부의 이주호(안병만 교육부장관시절 교육부 제1차관, 이후 교육부장관) ...",2215.035000,126.244892,-2103.035000,-14.244892
128636,153886,2018-02-28,2018-03-30,0,159,육아/교육,교육부와청와대는 총신대사태 보고만계실겁니까,총신대사태를바라보며 정부와 교육부는 뮐하고계십니까 학생들이 입학도 졸업도 개강도 못...,25.941047,126.244892,133.058953,32.755108
131279,156989,2018-03-03,2018-04-02,0,176,육아/교육,레인보우합창단을 돈벌이로 이용하는 한국다문화센터 조사해 주세요!!,다문화 가정 자녀를 지원한다는 명목으로 사리사욕을 채우는 한국다문화센터 비용 집행내...,6.013260,126.244892,169.986740,49.755108
131940,157825,2018-03-04,2018-04-03,0,78,육아/교육,전남 순천시 해룡면 신대지구 어린이집 입소대기 해소 해주세요.,안녕하세요.\n저는 전남 순천시 신대지구에 살고 맞벌이를 하고 있는 18개월 아이 ...,2974.230000,126.244892,-2896.230000,-48.244892
134252,160682,2018-03-07,2018-04-06,0,397,육아/교육,고용노동부 법정의무교육 교육비 삭감 민원,안녕하세요~\n저희는 사업주위탁 훈련기관의 영업대리점 입니다.\n제가 메일을 드리는...,787.490000,126.244892,-390.490000,270.755108
134544,161069,2018-03-08,2018-04-07,0,1731,육아/교육,민간 가정어린이집 운영자도 대한민국 국민 입니까?,국가사업인 어린이집 운영을 국가와 개인이 나누어 운영 한다면\n차별지원은 없어야 ...,387.770000,126.244892,1343.230000,1604.755108
134903,161509,2018-03-08,2018-04-07,0,88,육아/교육,중소기업 여성근로자의 육아휴직 제도...저희를 지켜주세요.,안녕하세요. 저는 60명 정도의 규모를 가진 중소기업에 5년동안 재직중인 여성 근로...,360.667500,126.244892,-272.667500,-38.244892
135142,161790,2018-03-08,2018-04-07,0,68,육아/교육,학생들의 인권도 보장해주세요 !,안녕하세요 저는 대한민국의 한 청소년입니다 제가 이렇게 글을 남기는 이유는 학생이라...,77.995000,126.244892,-9.995000,-58.244892
136466,163506,2018-03-11,2018-04-10,0,80,육아/교육,고등학교 생활기록부 변경 취소,안녕하세요 저는 올해 특성화고를 진학한 1학년 학생입니다 다름이 아니라 고등학교 생...,832.250000,5508.942308,-752.250000,-5428.942308
136569,163637,2018-03-11,2018-04-10,0,115,육아/교육,중고등학교 여학생 교복을 편하게 만들어주세요,현재 여중생 자녀를 둔 학부모입니다.\n불편한 교복을 입고 하루종일 공부하고 활동에...,14.675833,126.244892,100.324167,-11.244892
137003,164207,2018-03-11,2018-04-10,0,55,육아/교육,"여중생, 여고생의 교복에 대해 다시 한번 검토해주십시오.",안녕하십니까 . 저는 중학교에 재학중인 16살 학생입니다. 제가 이렇게 국민청원까지...,621.753333,126.244892,-566.753333,-71.244892
137318,164626,2018-03-12,2018-04-11,0,5877,육아/교육,"초등, 중등학교 스마트폰 사용을 제한해 주세요. (특히 단톡방)",제목 그대로 입니다.\n아이들에게 다양한 기회를 빼앗는 스카트폰의 폐해에 대하여\n...,1002.390000,126.244892,4874.610000,5750.755108
137821,165248,2018-03-13,2018-04-12,0,104,육아/교육,초등학교생활에 엄마역활을 빼주세요,초등학교에 들어가면 저학년때부터 고학년까지\n엄마들이 학교에와서 역할을 해야한다고 ...,89.531591,126.244892,14.468409,-22.244892
139689,167604,2018-03-16,2018-04-15,0,1403,육아/교육,김상곤교육부 장관 해임해주세요!!!,고1을 둔 엄마입니다.학부모총회때 두툼한 안내책자를 주었습니다.아무리 내용을 봐도 ...,77.115000,126.244892,1325.885000,1276.755108
143382,172267,2018-03-22,2018-04-21,0,299,육아/교육,순천 신대지구 유치원,사립유치원의 갑질횡포.도와주세요\n내용\n6세 학부모입니다. 이번에 변경된 영어교육...,309.955333,126.244892,-10.955333,172.755108
...,...,...,...,...,...,...,...,...,...,...,...,...
145664,175351,2018-03-25,2018-04-24,0,214,육아/교육,수시 줄이라니까 최저를 없애는 김상곤 교육부 장관 사퇴하세요.,전 국민 설문조사 한번 돌립시다. 수시가 응원받는지 정시가 응원받는지.\n강력한 드...,40.590203,126.244892,173.409797,87.755108
145730,175433,2018-03-25,2018-04-24,0,53,육아/교육,수능 최저기준 폐지에 강력하게 반대합니다,2019학년도 수능때부터 수능최저를 없애는 쪽으로 교육부가 일을 추진한다는 기사를 ...,2214.785000,126.244892,-2161.785000,-73.244892
145828,175551,2018-03-26,2018-04-25,0,332,육아/교육,미세먼지 관련 임시휴교,"지금 통합대기지수가 260으로 솟구치고 있으나 초,중,고등학교 학생들이 중국발 미세...",51.989227,126.244892,280.010773,205.755108
145928,175663,2018-03-26,2018-04-25,0,251,육아/교육,"학생부종합전형 비중 축소 및 정시 비중 확대, 수시 수능최저등급 폐지 철회를 부탁드립니다","작년 5월 문재인 대통령께서 내세우셨던 교육 정책이 수시 비중 확대, 수능의 절대평...",13457.070000,126.244892,-13206.070000,124.755108
145945,175688,2018-03-26,2018-04-25,0,61,육아/교육,수시비중보다 정시비중을 높여야합니다,저는 일년전까지 직장생활을 하던 스물여섯살 늦깍이 수험생입니다. 고졸출신으로 사회...,167.775000,126.244892,-106.775000,-65.244892
145969,175720,2018-03-26,2018-04-25,0,165,육아/교육,수능최저폐지 철회및 교육감사퇴,기준도 명확하지 않은 수시에 유일하게 실력미달자를 걸러줄수있는 수시최저를 없앤다는것...,6.455000,126.244892,158.545000,38.755108
146125,175911,2018-03-26,2018-04-25,0,110,육아/교육,수능 최저 폐지 및 정시 확대를 요구합니다.,지금 대학교에 재학 중인 학생입니다. 요즘 수능 최저 폐지 때문에 말이 많습니다....,911.960714,126.244892,-801.960714,-16.244892
146220,176037,2018-03-26,2018-04-25,0,84,육아/교육,수능최저 폐지 반대,고3학부모입니다. '수능최저 폐지 ' 를 듣고 너무 당황했습니다. 그것도 2019...,210.011000,126.244892,-126.011000,-42.244892
146420,176293,2018-03-26,2018-04-25,0,154,육아/교육,수능 최저 기준 폐지를 반대합니다.,현 입시제도에 가장 영향을 많이 받고 민감하게 반응할 수밖에 없는 고3 학생입니다....,17169.460000,126.244892,-17015.460000,27.755108
147168,177261,2018-03-27,2018-04-26,0,64,육아/교육,올해 수능부터 정시를 늘려주세요,존경하고 사랑하는 문재인대통령님이하 많은 분들의 수고에 감사의 인사를 드립니다\n현...,26.481667,126.244892,37.518333,-62.244892
147746,178003,2018-03-27,2018-04-26,0,338,육아/교육,전국 초.중.고등학교에 공기청정기 설치 의무화실시,요즘처럼 대기질 상태가 심각하게 나쁠때 우리 어린자녀들이 공부하는 학교에 공기청정기...,11.863559,126.244892,326.136441,211.755108
148347,178762,2018-03-28,2018-04-27,0,52,육아/교육,공정한 대입 ..수시 축소 정시 확대,아이들의 미래가 달린 대학입시입니다.\n누군가의 낡은 소신으로 밀어붙일 문제가 아닙...,21.326582,126.244892,30.673418,-74.244892
148728,179271,2018-03-29,2018-04-28,0,205,육아/교육,수능최저폐지 반대 및 학생부종합전형 축소를 원합니다,수능최저폐지 반대 및 학생부종합전형 축소를 원합니다,4.609111,126.244892,200.390889,78.755108
149538,180259,2018-03-29,2018-04-28,0,119,육아/교육,수시 폐지! 수능 2회 실시 청원 합니다.,학종부전형을 비롯한 모든 수시 폐지와 수능 2회 실시를 청원합니다.\n과거제도입이 ...,126.712500,126.244892,-7.712500,-7.244892
149636,180370,2018-03-30,2018-04-29,0,203,육아/교육,수시 최저 폐지 반대! 모두의 의견도 들어주세요.,안녕하세요. 현재 몸이 많이 안좋아 부득이하게 학교를 자퇴하고 검정고시를 본 청소년...,11089.775000,126.244892,-10886.775000,76.755108
149877,180668,2018-03-30,2018-04-29,0,1817,육아/교육,4차 산업혁명 시대에 맞게 학교 우유급식 신청을 앱이나 컴퓨터로 간편하게 하고 가정...,4차 산업혁명의 시대에 학교에서 수십 년 동안 가장 변하지 않는 것이 있다면 우유급...,422.315000,126.244892,1394.685000,1690.755108
149940,180741,2018-03-30,2018-04-29,0,345,육아/교육,대학원생 인건비 문제 해결해주세요,"1. 인건비 계좌 관리\n학생들 각자, 연구과제 인건비를 지급받을 계좌를 가지고 있...",786.842000,126.244892,-441.842000,218.755108
150083,180917,2018-03-30,2018-04-29,0,435,육아/교육,다산신도시 진건2초유3의 중투위통과를 요청합니다,"제목 : 다산 진건 2초, 유3 의 중투위 통과를 요청합니다.\n현재 다산 초등학교...",193.637500,126.244892,241.362500,308.755108
150358,181276,2018-03-30,2018-04-29,0,1936,육아/교육,2019학년도부터 정시확대 요구합니다,올해 수능을 준비하는 학생입니다.지금 2020학년도부터 정시확대를 하도록 교육부가 ...,793.581381,126.244892,1142.418619,1809.755108
150892,181919,2018-03-31,2018-04-30,0,129,육아/교육,"수시 수능 최저등급폐지 반대, 정시 대폭확대 희망합니다.","천하가 다 아는 불공정한 학종, 그들만을 위한 잔치,\n거기다 최저등급폐지까지 하...",63.045793,126.244892,65.954207,2.755108
151370,182544,2018-04-01,2018-05-01,0,327,육아/교육,홍신학원 법정부담금 24억 이자 붙혀서 받아내주십시오.,존경하는 대통령님\n대통령님이 만드시고자 하시는 공정하고 정의로운 세상을 만들기 위...,98.038571,126.244892,228.961429,200.755108
151641,182890,2018-04-01,2018-05-01,0,52,육아/교육,수능 정시 비율 확대,지금 수능 비율이 거의 20~30% 간당간당합니다.\n또 여기서 수능이 폐지 된다는...,47.954569,126.244892,4.045431,-74.244892
151744,183021,2018-04-02,2018-05-02,0,155,육아/교육,월요일을 주말로해주세요,갈수록 힘들어지는 나날과 휴식이 더욱이 중요해지는 이날에 5일나가고2일쉬기란 다음날...,67.851978,126.244892,87.148022,28.755108
152183,183587,2018-04-02,2018-05-02,0,86,육아/교육,아이들을 위해서 어린이집 증설 보육교사 처우개선이 필요합니다.,저출산 문제가 심화되고 있습니다.\n이유는 아이들을 나을 경제적 여건도 이들을 나아...,1040.720000,126.244892,-954.720000,-40.244892
152403,183882,2018-04-03,2018-05-03,0,84,육아/교육,수능 정시 확대 요청합니다,문재인대통령과 김상조 씨! 이 청원 꼭 봐주세요\n저는 학창시절을 몇년전에 겪은 대...,308.160000,126.244892,-224.160000,-42.244892
152461,183973,2018-04-03,2018-05-03,0,144,육아/교육,김상곤 교육부총리의 해임을 청원합니다.,지금 현재 고1 학생을 둔 학부모입니다.\n2018년 현재 대한민국 대입정책은 유사...,1846.230000,126.244892,-1702.230000,17.755108
156625,190975,2018-04-08,2018-05-08,0,116,육아/교육,"<보육교사의 호소> 저출산, 아동학대, 모든것은 하나로 이어져있습니다.",안녕하세요 부천 국공립 어린이집에서 9년째 근무하고 있는 보육교사입니다. 저는 보육...,1548.205000,126.244892,-1432.205000,-10.244892
158545,194252,2018-04-10,2018-05-10,0,59,육아/교육,아동당뇨 자동체크기허용,어제 방송에서 아동당뇨 자동체크기. 인슐린자동주입기 에대한 방송이나오더라구요 미국에...,8.290000,126.244892,50.710000,-67.244892
159000,195019,2018-04-11,2018-05-11,0,234,육아/교육,스마트폰 관련 제한,요즘 아이들 스마트폰의 유해 컨텐츠에 노출되어 걱정입니다\n학생들이 스마트폰을 보며...,83.370049,126.244892,150.629951,107.755108
159083,195195,2018-04-11,2018-05-11,0,63,육아/교육,김상곤 교육부 장관 사퇴,현재 수시가 대입에서 대부분을 차지하고 있음에도 경쟁률이 큰 이 마당에 수시에서 수...,213.480000,126.244892,-150.480000,-63.244892